# wi26_major.json

In [15]:
import json 
import pandas as pd

In [16]:
with open('./row/wi26_major.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

In [17]:
df = pd.json_normalize(data, record_path=['items'], meta=['description'])
df.rename(columns={
    'code': 'wi26_major_code', 'name': 'wi26_major_name', 'description': 'wi26_major_description'
    }, 
    inplace=True)
df.head()

  wi26_major_code wi26_major_name        wi26_major_description
0           WI100             에너지  WI26 대분류 (WI26 Major Sector)
1           WI110              화학  WI26 대분류 (WI26 Major Sector)
2           WI200            비철금속  WI26 대분류 (WI26 Major Sector)
3           WI210              철강  WI26 대분류 (WI26 Major Sector)
4           WI220              건설  WI26 대분류 (WI26 Major Sector)

In [18]:
df.shape

(26, 3)

# wi26_minor.json

In [19]:
with open('./row/wi26_minor.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

In [20]:
df_minor = pd.json_normalize(data, record_path=['items'], meta=['description'])
df_minor.rename(columns={
    'code': 'wi26_minor_code', 'name': 'wi26_minor_name', 'description': 'wi26_minor_description',
    'major_code': 'wi26_major_code'
    }, 
    inplace=True)
df_minor.head()

,wi26_minor_code,wi26_minor_name,wi26_major_code,wi26_minor_description
0,WI10010,에너지,WI100,WI26 소분류 (WI26 Minor Sector)
1,WI11010,화학,WI110,WI26 소분류 (WI26 Minor Sector)
2,WI20010,"포장재,종이와목재",WI200,WI26 소분류 (WI26 Minor Sector)
3,WI20020,비철금속,WI200,WI26 소분류 (WI26 Minor Sector)
4,WI21010,철강,WI210,WI26 소분류 (WI26 Minor Sector)

In [21]:
df_minor.shape

(48, 4)

## merge

In [22]:
df.columns

Index(['wi26_major_code', 'wi26_major_name', 'wi26_major_description'], dtype='str')

In [23]:
df_minor.columns

Index(['wi26_minor_code', 'wi26_minor_name', 'wi26_major_code',
       'wi26_minor_description'],
      dtype='str')

In [24]:
df = df.merge(df_minor, on='wi26_major_code', how='left')
df.head()

,wi26_major_code,wi26_major_name,wi26_major_description,wi26_minor_code,wi26_minor_name,wi26_minor_description
0,WI100,에너지,WI26 대분류 (WI26 Major Sector),WI10010,에너지,WI26 소분류 (WI26 Minor Sector)
1,WI110,화학,WI26 대분류 (WI26 Major Sector),WI11010,화학,WI26 소분류 (WI26 Minor Sector)
2,WI200,비철금속,WI26 대분류 (WI26 Major Sector),WI20010,"포장재,종이와목재",WI26 소분류 (WI26 Minor Sector)
3,WI200,비철금속,WI26 대분류 (WI26 Major Sector),WI20020,비철금속,WI26 소분류 (WI26 Minor Sector)
4,WI210,철강,WI26 대분류 (WI26 Major Sector),WI21010,철강,WI26 소분류 (WI26 Minor Sector)

In [25]:
df.shape

(48, 6)

# wi26_wics_mapping.json

In [26]:
with open('./row/wi26_wics_mapping.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
    
df_wics_mapping = pd.json_normalize(data, record_path=['items'])
df_wics_mapping.head()

,wics_minor_code,wics_minor_name,wi26_major_code,wi26_minor_code,wi26_minor_name
0,101010,에너지장비및서비스,WI100,WI10010,에너지
1,101020,석유와가스,WI100,WI10010,에너지
2,151010,화학,WI110,WI11010,화학
3,151030,포장재,WI200,WI20010,"포장재,종이와목재"
4,151040,비철금속,WI200,WI20020,비철금속

In [10]:
df_wics_mapping.shape

(79, 5)

## merge

In [27]:
df_wics_mapping.columns

Index(['wics_minor_code', 'wics_minor_name', 'wi26_major_code',
       'wi26_minor_code', 'wi26_minor_name'],
      dtype='str')

In [28]:
df.columns

Index(['wi26_major_code', 'wi26_major_name', 'wi26_major_description',
       'wi26_minor_code', 'wi26_minor_name', 'wi26_minor_description'],
      dtype='str')

In [29]:
df = df.merge(df_wics_mapping[['wics_minor_code', 'wics_minor_name', 'wi26_minor_code']], on='wi26_minor_code', how='left')
df.head()

,wi26_major_code,wi26_major_name,wi26_major_description,wi26_minor_code,wi26_minor_name,wi26_minor_description,wics_minor_code,wics_minor_name
0,WI100,에너지,WI26 대분류 (WI26 Major Sector),WI10010,에너지,WI26 소분류 (WI26 Minor Sector),101010,에너지장비및서비스
1,WI100,에너지,WI26 대분류 (WI26 Major Sector),WI10010,에너지,WI26 소분류 (WI26 Minor Sector),101020,석유와가스
2,WI110,화학,WI26 대분류 (WI26 Major Sector),WI11010,화학,WI26 소분류 (WI26 Minor Sector),151010,화학
3,WI200,비철금속,WI26 대분류 (WI26 Major Sector),WI20010,"포장재,종이와목재",WI26 소분류 (WI26 Minor Sector),151030,포장재
4,WI200,비철금속,WI26 대분류 (WI26 Major Sector),WI20010,"포장재,종이와목재",WI26 소분류 (WI26 Minor Sector),151060,종이와목재

In [30]:
df.shape

(79, 8)

In [31]:
df.isnull().sum().sum()

np.int64(0)

In [32]:
df.to_csv('wi26.csv', index=False, encoding='utf-8', header=True)