In [1]:
import os

import pandas as pd
from dotenv import load_dotenv

from dart_api import fetch_financial_statements, split_by_statement_type

load_dotenv()
api_key = os.getenv("DART_API_KEY")

# 회사 코드 조회

In [2]:
df_com = pd.read_csv("./data/dart_company_2026.csv", dtype={'DART_CD': str})[['DART_CD', 'CMP_KOR']]

In [3]:
df_com.head()

    DART_CD  CMP_KOR
0  00181712       SK
1  00631518  SK이노베이션
2  00138279    S-Oil
3  00162461    한화솔루션
4  00500254       GS

In [4]:
df_com[df_com['CMP_KOR'] == "삼성전자"]

       DART_CD CMP_KOR
2096  00126380    삼성전자

# 데이터 수집

## 2025

In [30]:
import pandas as pd
import time
from tqdm.auto import tqdm

balance_sheet = pd.DataFrame() # 대차대조표 (sj_div == BS)
income_statement = pd.DataFrame() # 손익·포괄손익 (IS, CIS)
cash_flow = pd.DataFrame() # 현금흐름표 (CF)

bsns_year = "2025"  # 사업연도

for dart_cd in tqdm(df_com['DART_CD'].to_list(), desc="dart..", leave=True):
    time.sleep(0.5)
    try:
        # 단일회사 전체 재무제표
        df_all = fetch_financial_statements(
            dart_cd,
            bsns_year,
            crtfc_key=api_key,
            reprt_code="11011", # # reprt_code: 11011 사업보고서, 11012 반기, 11013 1분기, 11014 3분기
            fs_div="CFS"  # CFS: 연결, OFS: 별도
        )
        # 종류별 분리
        tables = split_by_statement_type(df_all)
        balance_sheet = pd.concat([balance_sheet, tables["balance_sheet"]], axis=0)
        income_statement = pd.concat([income_statement, tables["income_statement"]], axis=0)
        cash_flow = pd.concat([cash_flow, tables["cash_flow"]], axis=0)
    except Exception as e:
        # print(e)
        continue

dart..:   0%|          | 0/2578 [00:00<?, ?it/s]

In [32]:
balance_sheet['bsns_year'] = bsns_year
income_statement['bsns_year'] = bsns_year
cash_flow['bsns_year'] = bsns_year

In [37]:
balance_sheet.head()

,rcept_no,reprt_code,bsns_year,corp_code,sj_div,sj_nm,account_id,account_nm,account_detail,thstrm_nm,thstrm_amount,frmtrm_nm,frmtrm_amount,bfefrmtrm_nm,bfefrmtrm_amount,ord,currency,thstrm_add_amount
0,20260318001157,11011,2025,00181712,BS,재무상태표,ifrs-full_Assets,자산총계,-,제 35 기,213519668000000,제 34 기,214977754000000,제 33 기,206970264000000,7,KRW,NaN
1,20260318001157,11011,2025,00181712,BS,재무상태표,ifrs-full_CurrentAssets,유동자산,-,제 35 기,71676598000000,제 34 기,67431274000000,제 33 기,64834622000000,8,KRW,NaN
2,20260318001157,11011,2025,00181712,BS,재무상태표,dart_ShortTermOtherReceivablesNet,미수금,-,제 35 기,2560879000000,제 34 기,3114522000000,제 33 기,3060312000000,9,KRW,NaN
3,20260318001157,11011,2025,00181712,BS,재무상태표,ifrs-full_CashAndCashEquivalents,현금및현금성자산,-,제 35 기,25214132000000,제 34 기,24647042000000,제 33 기,22683670000000,10,KRW,NaN
4,20260318001157,11011,2025,00181712,BS,재무상태표,ifrs-full_CurrentTradeReceivables,매출채권,-,제 35 기,13133418000000,제 34 기,13454372000000,제 33 기,13879388000000,11,KRW,NaN

In [38]:
balance_sheet.shape, income_statement.shape, cash_flow.shape

((91056, 18), (55629, 18), (97319, 18))

In [39]:
balance_sheet.to_csv('./data/balance_sheet_2025.csv', index=False, encoding='utf-8', header=True)
income_statement.to_csv('./data/income_statement_2025.csv', index=False, encoding='utf-8', header=True)
cash_flow.to_csv('./data/cash_flow_2025.csv', index=False, encoding='utf-8', header=True)

## 2024

In [40]:
import pandas as pd
import time
from tqdm.auto import tqdm

balance_sheet = pd.DataFrame() # 대차대조표 (sj_div == BS)
income_statement = pd.DataFrame() # 손익·포괄손익 (IS, CIS)
cash_flow = pd.DataFrame() # 현금흐름표 (CF)

bsns_year = "2024"  # 사업연도

for dart_cd in tqdm(df_com['DART_CD'].to_list(), desc="dart..", leave=True):
    time.sleep(0.5)
    try:
        # 단일회사 전체 재무제표
        df_all = fetch_financial_statements(
            dart_cd,
            bsns_year,
            crtfc_key=api_key,
            reprt_code="11011", # # reprt_code: 11011 사업보고서, 11012 반기, 11013 1분기, 11014 3분기
            fs_div="CFS"  # CFS: 연결, OFS: 별도
        )
        # 종류별 분리
        tables = split_by_statement_type(df_all)
        balance_sheet = pd.concat([balance_sheet, tables["balance_sheet"]], axis=0)
        income_statement = pd.concat([income_statement, tables["income_statement"]], axis=0)
        cash_flow = pd.concat([cash_flow, tables["cash_flow"]], axis=0)
    except Exception as e:
        # print(e)
        continue

dart..:   0%|          | 0/2578 [00:00<?, ?it/s]

In [41]:
balance_sheet['bsns_year'] = bsns_year
income_statement['bsns_year'] = bsns_year
cash_flow['bsns_year'] = bsns_year

In [42]:
balance_sheet.shape, income_statement.shape, cash_flow.shape

((88993, 21), (54221, 21), (95321, 21))

In [43]:
balance_sheet.to_csv('./data/balance_sheet_2024.csv', index=False, encoding='utf-8', header=True)
income_statement.to_csv('./data/income_statement_2024.csv', index=False, encoding='utf-8', header=True)
cash_flow.to_csv('./data/cash_flow_2024.csv', index=False, encoding='utf-8', header=True)

## 2023

In [5]:
from dart_api import save_financial_statements_by_year

balance_sheet, income_statement, cash_flow = save_financial_statements_by_year(df_com, "2023")

balance_sheet.shape, income_statement.shape, cash_flow.shape

dart..:   0%|          | 0/2578 [00:00<?, ?it/s]

Saved 2023 financial statements

((85680, 18), (52300, 18), (93571, 18))

In [6]:
balance_sheet.head(2)

,rcept_no,reprt_code,bsns_year,corp_code,sj_div,sj_nm,account_id,account_nm,account_detail,thstrm_nm,thstrm_amount,frmtrm_nm,frmtrm_amount,bfefrmtrm_nm,bfefrmtrm_amount,ord,currency,thstrm_add_amount
0,20240319000757,11011,2023,00181712,BS,재무상태표,ifrs-full_Assets,자산총계,-,제 33 기,206970264000000,제 32 기,194505860000000,제 31 기,165368363000000,7,KRW,NaN
1,20240319000757,11011,2023,00181712,BS,재무상태표,ifrs-full_CurrentAssets,유동자산,-,제 33 기,64834622000000,제 32 기,64993579000000,제 31 기,49193206000000,8,KRW,NaN

## 2022

In [7]:
from dart_api import save_financial_statements_by_year

balance_sheet, income_statement, cash_flow = save_financial_statements_by_year(df_com, "2022")

balance_sheet.shape, income_statement.shape, cash_flow.shape

dart..:   0%|          | 0/2578 [00:00<?, ?it/s]

Saved 2022 financial statements

((80568, 18), (48478, 18), (88924, 18))

In [8]:
balance_sheet.head(2)

,rcept_no,reprt_code,bsns_year,corp_code,sj_div,sj_nm,account_id,account_nm,account_detail,thstrm_nm,thstrm_amount,frmtrm_nm,frmtrm_amount,bfefrmtrm_nm,bfefrmtrm_amount,ord,currency,thstrm_add_amount
0,20230321001347,11011,2022,00181712,BS,재무상태표,ifrs-full_CurrentAssets,유동자산,-,제 32 기,64993579000000,제 31 기,49193206000000,제 30 기,38052297000000,1,KRW,NaN
1,20230321001347,11011,2022,00181712,BS,재무상태표,ifrs-full_CashAndCashEquivalents,현금및현금성자산,-,제 32 기,21393853000000,제 31 기,12317555000000,제 30 기,10096940000000,2,KRW,NaN

## 2021

In [9]:
from dart_api import save_financial_statements_by_year

balance_sheet, income_statement, cash_flow = save_financial_statements_by_year(df_com, "2021")

balance_sheet.shape, income_statement.shape, cash_flow.shape

dart..:   0%|          | 0/2578 [00:00<?, ?it/s]

Saved 2021 financial statements

((76629, 18), (46774, 18), (85502, 18))

In [10]:
balance_sheet.head(2)

,rcept_no,reprt_code,bsns_year,corp_code,sj_div,sj_nm,account_id,account_nm,account_detail,thstrm_nm,thstrm_amount,frmtrm_nm,frmtrm_amount,bfefrmtrm_nm,bfefrmtrm_amount,ord,currency,thstrm_add_amount
0,20220816001773,11011,2021,00181712,BS,재무상태표,ifrs-full_CurrentAssets,유동자산,-,제 31 기,49193206000000,제 30 기,38052297000000,제 29 기,40015360000000,1,KRW,NaN
1,20220816001773,11011,2021,00181712,BS,재무상태표,ifrs-full_CashAndCashEquivalents,현금및현금성자산,-,제 31 기,12317555000000,제 30 기,10096940000000,제 29 기,7981755000000,2,KRW,NaN